# A set of pre-defined stages and job template.
stages:
  - build
  - test
  - deploy
  - verify
  - recycle

.check: 
  stage: test
  only:
    - merge_requests

.coverage:      
  stage: deploy
  artifacts:
    paths:
      - public
    expire_in: 1 days
  only:
    - merge_requests

.merged:
  only:
    variables:
      - $CI_COMMIT_DESCRIPTION =~ /See merge request/
